name: Generate Image Metadata

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-metadata:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow
    
    - name: Run metadata script
      run: python image_indexer.py
    
    - name: Upload metadata file
      uses: actions/upload-artifact@v3
      with:
        name: image-metadata
        path: image_metadata.json
